apiVersion: apps/v1
kind: Deployment
metadata:
  name: citas-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citas-postgres
  template:
    metadata:
      labels:
        app: citas-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: citasdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
